baseURL = "https://eknoes.de/"
languageCode = "en-us"
title = "Eknoes Blog"
theme = "hyde"

[Menus]
  main = [
      {Name = "About", URL = "/about"},
      {Name = "Github", URL = "https://github.com/eknoes/"},
      {Name = "Twitter", URL = "https://twitter.com/soenke_hu"},
  ]

[params]
  description = "Graduate CS student with focus on Privacy & Security topics"
  themeColor = "theme-base-0c"
  copyright = " "

[markup]
  [markup.highlight]
    tabWidth = 2
